# Generated by Django 6.0.6 on 2026-06-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Varlık Adı')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Sembol')),
                ('asset_type', models.CharField(choices=[('BIST', 'Borsa İstanbul (TL)'), ('US', 'Amerikan Borsası (USD)'), ('EU', 'Avrupa Borsası (EUR)'), ('CRYPTO', 'Kripto Para (USD)')], max_length=10, verbose_name='Varlık Türü')),
            ],
            options={
                'verbose_name': 'varlık',
                'verbose_name_plural': 'Varlıklar',
            },
        ),
        migrations.CreateModel(
            name='IndicativeExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Tarih')),
                ('usd_forex_buying', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='USD/TRY')),
                ('eur_forex_buying', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='EUR/TRY')),
            ],
            options={
                'verbose_name': 'Kur',
                'verbose_name_plural': 'TCMB Forex Alış Kurları',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InflationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Değer')),
            ],
            options={
                'verbose_name': 'endeks',
                'verbose_name_plural': 'Yurtiçi Üretici Endeksi',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='İşlem Tarihi')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Alış'), ('SELL', 'Satış')], max_length=4, verbose_name='İşlem Türü')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Adet')),
                ('price_foreign', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Birim Fiyat (Döviz/TL)')),
                ('commission_foreign', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Komisyon (Döviz/TL)')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=18, null=True, verbose_name='Kur')),
                ('yi_ufe_index', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Yİ-ÜFE')),
                ('remaining_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Kalan Stok')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.asset', verbose_name='Varlık')),
            ],
            options={
                'verbose_name': 'transaksiyon',
                'verbose_name_plural': 'Transaksiyonlar',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Satış Tarihi')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Satılan Adet')),
                ('sale_price_foreign', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Satış Fiyatı')),
                ('sale_commission_foreign', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Satış Komisyonu')),
                ('sale_exchange_rate', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Satış Kuru')),
                ('sale_index', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_hash', models.TextField(verbose_name='Alış İşlem Kodu (Hash)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
            ],
            options={
                'verbose_name': 'satış',
                'verbose_name_plural': 'Satışlar',
                'constraints': [models.UniqueConstraint(fields=('asset', 'sale_date', 'quantity', 'purchase_hash'), name='unique_fifo_sale')],
            },
        ),
    ]
